### ISSUE TITLE
Build-System

### ISSUE THREAD

**Issue by derhuerst** [twaddle/zelebriert#2]
Es fehlt ein Build-System, mit dem sich diese schnöde Liste von Wörtern in eine aufdesignte, interaktive Flash-Präsentation verwandeln lässt. Ich schlage das Designer-Tool schlechthin – [*Gulp*](http://gulpjs.com/) – vor.

**Comment by twaddle** [comment]
Das einzige, was hier momentan fehlt, ist Brenck, Brenckdiewand und umgebrenckt.

**Comment by derhuerst** [comment]
Im Sinne der Transparenz: 28d131f
