### ISSUE TITLE
move list to readme.md

### ISSUE THREAD

**Issue by derhuerst** [twaddle/zelebriert#4]
There is really no reason to maintain the list in another file, both from a theoretical and a perspective of usability. Also, maintaining the list in Markdown would provide additional semantical information.

**Comment by twaddle** [comment]
I am sorry, but inexperienced contributors like you are not expected to discuss this god-given structure. Also, at some unspecified point in the future the list might be split into several. Please do not further distract the mainline maintainers like myself and consider reading the soon-to-be-published contribution guideline before posting another comment.
